### ISSUE TITLE
SVN Error E155021

### ISSUE THREAD

**Issue by patrickhousley** [andischerer/atom-svn#10]
I am getting the bellow error in the Atom console. I do not get this error when working directly in my terminal. I am currently running OS X 10.10.5. Error is occurring in function `getSvnWorkingCopyRevision`. The command being ran is `svnversion "<directory>" -n`. This command also returns with no problem in my terminal.

```
SVN svn-utils Error: svn: E155021: This client is too old to work with the working copy
```

**Comment by andischerer** [comment]
With the command line client, you have to manually upgrade your working copy format by issuing the command `svn upgrade`

See here for details http://subversion.apache.org/docs/release-notes/1.7.html#wc-upgrade

Which version of svn are you using ?

**Comment by patrickhousley** [comment]
svn upgrade is not needed. Terminal output is below. Branch was checked out with the same version of svn I have installed on my machine.

```
mac:REL_20151029_3.4.7 $ svn upgrade
mac:REL_20151029_3.4.7 $ svn --version
svn, version 1.8.13 (r1667537)
   compiled Jun  5 2015, 19:21:21 on x86_64-apple-darwin14.3.0
```

**Comment by andischerer** [comment]
Could you start atom from command line in your project directory in devmode `atom . -d` and post the console logs from atom devtools(`View -> Developer -> Toggle Developer Tools -> Console Tab`)

**Comment by patrickhousley** [comment]
I did as you said and did not see any errors. So, I opened Atom from the command line again without the `-d` flag and still no errors. This seems to only happen when I open atom from the launcher or from the Applications folder.

**Comment by andischerer** [comment]
Do you have multiple svn versions installed ?

**Comment by patrickhousley** [comment]
```
user-mac:~ user$ brew list svn
/usr/local/Cellar/subversion/1.8.13/bin/svn
/usr/local/Cellar/subversion/1.8.13/bin/svnadmin
/usr/local/Cellar/subversion/1.8.13/bin/svndumpfilter
/usr/local/Cellar/subversion/1.8.13/bin/svnlook
/usr/local/Cellar/subversion/1.8.13/bin/svnmucc
/usr/local/Cellar/subversion/1.8.13/bin/svnrdump
/usr/local/Cellar/subversion/1.8.13/bin/svnserve
/usr/local/Cellar/subversion/1.8.13/bin/svnsync
/usr/local/Cellar/subversion/1.8.13/bin/svnversion
/usr/local/Cellar/subversion/1.8.13/etc/bash_completion.d/subversion
/usr/local/Cellar/subversion/1.8.13/include/subversion-1/ (44 files)
/usr/local/Cellar/subversion/1.8.13/lib/libsvn_client-1.0.dylib
/usr/local/Cellar/subversion/1.8.13/lib/libsvn_delta-1.0.dylib
/usr/local/Cellar/subversion/1.8.13/lib/libsvn_diff-1.0.dylib
/usr/local/Cellar/subversion/1.8.13/lib/libsvn_fs-1.0.dylib
/usr/local/Cellar/subversion/1.8.13/lib/libsvn_fs_fs-1.0.dylib
/usr/local/Cellar/subversion/1.8.13/lib/libsvn_fs_util-1.0.dylib
/usr/local/Cellar/subversion/1.8.13/lib/libsvn_ra-1.0.dylib
/usr/local/Cellar/subversion/1.8.13/lib/libsvn_ra_local-1.0.dylib
/usr/local/Cellar/subversion/1.8.13/lib/libsvn_ra_serf-1.0.dylib
/usr/local/Cellar/subversion/1.8.13/lib/libsvn_ra_svn-1.0.dylib
/usr/local/Cellar/subversion/1.8.13/lib/libsvn_repos-1.0.dylib
/usr/local/Cellar/subversion/1.8.13/lib/libsvn_subr-1.0.dylib
/usr/local/Cellar/subversion/1.8.13/lib/libsvn_wc-1.0.dylib
/usr/local/Cellar/subversion/1.8.13/lib/ (26 other files)
/usr/local/Cellar/subversion/1.8.13/libexec/serf/ (7 files)
/usr/local/Cellar/subversion/1.8.13/libexec/svn-tools/ (13 files)
/usr/local/Cellar/subversion/1.8.13/libexec/ (3 files)
/usr/local/Cellar/subversion/1.8.13/share/man/ (10 files)
user-mac:~ user$ 
```

**Comment by patrickhousley** [comment]
I did find one that is installed as part of XCode Developer Tools and it is version 1.7 but it is not in my PATH variable nor is it linked in any of the folders in my path variable.

**Comment by andischerer** [comment]
hmm.
Could you start atom from launcher, then `view -> developer -> open in devmode -> choose project root` and check the version number from devtools console:

![2015-11-04 16_48_33-config xml - d__work_cordova_myke-offline - atom](https://cloud.githubusercontent.com/assets/930604/10943297/28b6d22a-8314-11e5-8087-642f65bf0b20.png)

**Comment by patrickhousley** [comment]
```
Window load time: 1078ms
svn-utils.coffee:60 SVN svn-utils repoRootPath /Users/user/Documents/projects/project/branches/REL_20151029_3.4.7
svn-utils.coffee:69 SVN svn-utils binary version: 1.8.13
svn-repository.coffee:130 SVN svn-repository setWorkingDirectory /Users/user/Documents/projects/project/branches/REL_20151029_3.4.7
svn-repository.coffee:408 SVN svn-repository refreshStatus
svn-utils.coffee:283 SVN svn-utils Error: svn: E155021: This client is too old to work with the working copy at
'/Users/user/Documents/projects/project/branches/REL_20151029_3.4.7' (format 31).
You need to get a newer Subversion client. For more details, see
  http://subversion.apache.org/faq.html#working-copy-format-change


'/Users/user/Documents/projects/sprint.com/branches/REL_20151029_3.4.7' (format 31).
You need to get a newer Subversion client. For more details, see
  http://subversion.apache.org/faq.html#working-copy-format-change
```

**Comment by patrickhousley** [comment]
@andischerer I am convinced this is directly related to https://github.com/atom/electron/issues/550. I found the pre-installed svn commands in /usr/bin. Since Atom is not properly inheriting my profile's `$PATH` variable, it is looking in /usr/bin first.

**Comment by patrickhousley** [comment]
Corrected the issue by installing https://github.com/hurrymaplelad/atom-fix-path. I also opened a bug with electron to see if they can maybe implement https://github.com/sindresorhus/fix-path so users wont need to do this.
