### ISSUE TITLE
Freezes on file save

### ISSUE THREAD

**Issue by knubbbe** [andischerer/atom-svn#11]
When I save a file with this package enabled the editor freezes for about 5-10 seconds each time.
Anything I can do to prevent that?

Using version 0.0.8
Atom: 1.2.0-Beta0
SVN version: 1.8.8
Linux Mint 17.2 x64

Edit: When I disabled symbol-gen package (threw errors) it went down to 2 second freeze.

**Comment by Arcanemagus** [comment]
Just a note: Much of this is due to this currently being a shell wrapper around SVN commands, instead of native integration: https://github.com/andischerer/atom-svn/issues/2#issuecomment-118989373

The rest of it is that `svn` is just slow for things like this.

**Comment by andischerer** [comment]
duplicate, please subscribe here #2
