### ISSUE TITLE
Another atom-svn package, with different functionality

### ISSUE THREAD

**Issue by kgrossjo** [andischerer/atom-svn#15]
Hi Andi,

some time ago I wrote https://github.com/kgrossjo/atom-svn which unfortunately has the same name as your package.  Also I don't have much time to work on my package anymore.

I think I should rename my package (to `atom-svn-status`, maybe?).  I'm not sure if it makes sense to rename yours to `atom-svn-diff`.  Or do we want to combine both pieces of functionality into one package?

Let me know what you think.

Kai

**Comment by kgrossjo** [comment]
So.  This was a bit silly.  I haven't even published my package yet.  So I just renamed the github repo to https://github.com/kgrossjo/atom-svn-status and I renamed the Atom package (for whenever I actually do publish it).

But still if you would like to take over this functionality, that would be pretty great :-)

**Comment by 0rvar** [comment]
I think your package looks great. However, the functionality seems orthogonal to this package, so merging the two would not be a good thing in my opinion - i prefer small packages that do one thing well. 

I'll close this issue for the time being.
