### ISSUE TITLE
Diffs/colours not visible on Atom 1.5.3/atom-svn 0.0.9

### ISSUE THREAD

**Issue by ghost** [andischerer/atom-svn#18]
I am a newcomer to Atom and use GIT and (forced to) use SVN at work. I installed the atom-svn plugin but can't get it to work which is frustrating.

Atom 1.5.3
Theme Atom-Dark/Atom-Dark
SVN plugin 0.0.9
git-diff 0.57.0 plugin installed
SVN client 1.7.14
SVN Server 1.8.8
'svn' in $PATH
RedHat Linux 7 (3.10.0-327.10.1.el7.x86_64)

Git highlights modified files in orange and new (green), changed lines (orange), deleted lines (pink).
Treeview displays modified files (directories) in orange.

However, for a SVN controlled file, no colours or diffs are visible.

Am I missing something obvious ?

**Comment by andischerer** [comment]
For a more detailed report please start atom from commandline at your projectroot with 

```
atom -d .
```

Open the atom devtools(View>Developer>Toggle Developer Tools) and switch to console tab if necessary and post the output here

**Comment by ghost** [comment]
Thanks for the quick reply. I think I will run another test with a local SVN repo which means I don't have to use my corporate VPN and then post the console if necessary.,

**Comment by ghost** [comment]
I did some more tests using local SVN repos and comparing with GIT. It appears that the first Project that is under SVN control works fine but any subsequent ones don't. This differs from GIT where all projects are coloured appropriately.

Not a big issue for me as I can workaround it easily enough and maybe that's the intended behaviour (performance ?)

Thanks for this package - SVN support was a requirement for me as a long time Emacs/VCS user.

Here is the console output from 'atom -d' with two local SVN repos (myrepo, repo2) with Treeview and explicitly selecting files in 'repo2'.

SVN svn-utils repoRootPath /home/andy/devel/myrepo
svn-utils.coffee:69 SVN svn-utils binary version: 1.7.14
svn-repository.coffee:133 SVN svn-repository setWorkingDirectory /home/andy/devel/myrepo
svn-repository.coffee:420 SVN svn-repository refreshStatus
svn-utils.coffee:85 SVN svn-utils revision 1
svn-utils.coffee:92 SVN svn-utils url http://localhost/svn/myrepo
svn-utils.coffee:208 SVN svn-utils getLineDiffs Object
svn-utils.coffee:208 SVN svn-utils getLineDiffs Object
svn-utils.coffee:208 SVN svn-utils getLineDiffs Object
svn-utils.coffee:208 SVN svn-utils getLineDiffs Object
svn-utils.coffee:208 SVN svn-utils getLineDiffs Object
svn-utils.coffee:208 SVN svn-utils getLineDiffs Object
svn-utils.coffee:208 SVN svn-utils getLineDiffs Object
svn-repository.coffee:261 SVN svn-repository getDirectoryStatus /home/andy/devel/myrepo
svn-repository.coffee:144 SVN svn-repository isProjectAtRoot true
svn-repository.coffee:261 SVN svn-repository getDirectoryStatus /home/andy/devel/myrepo/.svn
svn-repository.coffee:296 SVN svn-repository getCachedPathStatus /home/andy/devel/myrepo/hello.txt 256
svn-repository.coffee:296 SVN svn-repository getCachedPathStatus /home/andy/devel/myrepo/newfile.txt 128
svn-repository.coffee:261 SVN svn-repository getDirectoryStatus /home/andy/devel/myrepo/project
svn-repository.coffee:296 SVN svn-repository getCachedPathStatus /home/andy/devel/myrepo/project/tester.py 1
/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:452 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:452 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
index.js:52 Window load time: 3337ms
/home/andy/.atom/packages/svn/lib/svn-utils.coffee:235 SVN svn-utils getLineDiffs Object
/home/andy/.atom/packages/svn/lib/svn-utils.coffee:235 SVN svn-utils getLineDiffs Object
/home/andy/.atom/packages/svn/lib/svn-utils.coffee:235 SVN svn-utils getLineDiffs Object
/home/andy/.atom/packages/svn/lib/svn-utils.coffee:235 SVN svn-utils getLineDiffs Object
/home/andy/.atom/packages/svn/lib/svn-utils.coffee:235 SVN svn-utils getLineDiffs Object
/home/andy/.atom/packages/svn/lib/svn-utils.coffee:235 SVN svn-utils getLineDiffs Object
/home/andy/.atom/packages/svn/lib/svn-utils.coffee:235 SVN svn-utils getLineDiffs Object

**Comment by ghost** [comment]
Screenshot
![screenshot from 2016-02-29 19-54-21](https://cloud.githubusercontent.com/assets/823262/13407016/61d0f156-df1e-11e5-91de-cb0fde1bfcd3.png)

**Comment by andischerer** [comment]
Support for multiple project folders is currently not available.
See here #12 for further updates.
