### ISSUE TITLE
Help installing on Windows

### ISSUE THREAD

**Issue by Tyree** [andischerer/atom-svn#19]
Sorry for the probable noob question, but where is the svn binary I need to add to PATH  on Windows 7? I have Tortoise SVN installed as well as Smart SVN. Do those install an svn binary?

Thanks!

**Comment by Tyree** [comment]
Nevermind. I see that I can install svn.exe (command line tools) as an option with TortoiseSVN. Did so and added the path (C:\Program Files\TortoiseSVN\bin\svn.exe) to the system PATH. Restarted Atom and it seems to be working.
Thanks!

**Comment by ghost** [comment]
I'm facing the same issue and can't get my hands on the svn.exe file.  No admin rights to even reinstall.  Perhaps Cygwin can do the trick...

**Comment by Tyree** [comment]
You can get the svn.exe with TortoiseSVN.

**Comment by ghost** [comment]
Right, I have the .msi, but no admin rights to reinstall.  I currently don't have svn.exe since the sysadmin installed it without the CLI tools... :(

**Comment by Tyree** [comment]
Ah, I gotcha. Go here and download the Apache Subversion command line tools. The svn.exe is in the bin folder. No need to install. https://www.visualsvn.com/downloads/

**Comment by ghost** [comment]
Nice, I stopped searching after a short while.  Thanks for the pointer.
