### ISSUE TITLE
Load package asynchronously

### ISSUE THREAD

**Issue by lwis** [andischerer/atom-svn#2]
Atom hangs for a while on large projects, I believe this could be fixed by loading the package and updating the UI asynchronously.

**Comment by andischerer** [comment]
I noticed this too. But atoms repository api is currently synchronous, see [here](https://github.com/atom/atom/blob/master/src/git-repository-provider.coffee#L46-L47)

**Comment by lwis** [comment]
The difference being that git returns (almost) instantly, SVN (sadly) does
not.

**Comment by andischerer** [comment]
Git outperforms svn in managing large repos and atom is using native c
bindings(libgit2) for git integration. I havent seen any native bindings
for svn in node. I use a binary wrapper, which is probably a loss in
performance.

Lewis Juggins notifications@github.com schrieb am Mo., 6. Juli 2015 20:47:

> The difference being that git returns (almost) instantly, SVN (sadly) does
> not.
>

**Comment by just-be-dev** [comment]
@andischerer, it seems to me that the API is designed to be asynchronous but atom's git implementation simply doesn't take advantage of it. They're calling the api asynchronously in the [spec](https://github.com/atom/atom/blob/8b40c3aaeba4c98730b8d5451b6aba1f09b55911/spec/git-repository-provider-spec.coffee#L27-L28). 

Granted you'd still have to figure out a way to get your SVN call to be async. I might look into adding a PR though, because I use SVN at work but this plugin tends to lock up atom whenever I open one of our projects (because they're huge).

**Comment by gfviegas** [comment]
is there any news here? This plugin is taking almost 20s to open project, source timecop!

**Comment by zonyitoo** [comment]
Any news here? It is too slow, it always blocks the Atom for seconds!

**Comment by andischerer** [comment]
I've released a new version(0.0.9) with several performace/startup improvements.

**Comment by sneakypete81** [comment]
I had previously found this to be unusable on large repos.
The changes in 0.0.9 make it much, much faster - thanks!

**Comment by andischerer** [comment]
nice to hear :sunglasses:

**Comment by zonyitoo** [comment]
Much better than before, thank a lot!

**Comment by rfreitas** [comment]
Still makes my Atom unresponsive at times and really slows down load, it says it takes 8 seconds to load. My repo is huge btw, it's a production repo of a full smartphone.

**Comment by 0rvar** [comment]
@rfreitas do you still have performance issues with the latest version?

**Comment by sneakypete81** [comment]
With the latest v0.0.12, timecop reports over 8 seconds to activate the package for a large repo:
![screenshot from 2016-07-06 08 58 12](https://cloud.githubusercontent.com/assets/38854/16611260/fc0c6c80-4357-11e6-9f62-86279f1dd923.png)

Much, much better than before, but still quite slow.

**Comment by rfreitas** [comment]
@awestroke I'm no longer working with that svn repo, or svn for that matter. As far as important details go, it was a very big project, around 25GB.
