### ISSUE TITLE
Changes of Code or anything else is not Colored

### ISSUE THREAD

**Issue by atodicebear** [andischerer/atom-svn#29]
I have installed it over command line once and over Atom +Install Packages once, both times it was not working.
Git-Diff is enabled. And more setups are not explained to get it running.
I worked earlier with Atom and Github there it was working, changed Files were Orange.
This packet
[https//atom.io/packages/tortoise-svn](url)
is working fine with Atom. It shows changed Files which I can Commit then.
So svn setup is working fine it has something to be with the Package...

Solutions?

**Comment by drchuckradio** [comment]
I've noticed the same thing.  Not sure what changed, but my projects are in SVN, and there's no indication that my files had changed.  I've even re-installed Atom and my packages, but still not working.  I'm using Atom 1.11.2 and svn 0.0.13.

Also, there's no indication in the status bar that I'm working on a project that's in an SVN repository.  I used to get that, too.

**Comment by atodicebear** [comment]
@andischerer @awestroke  Something on that?

**Comment by drchuckradio** [comment]
I figured it out, turns out `svn.exe` was no longer in my Windows environment path:

> This package uses a binary svn wrapper. So you have to put your svn-binary in your os searchpath.

I put my TortoiseSVN bin folder on my path, and everything started working again.

**Comment by atodicebear** [comment]
could you post a detailed explanation please?

**Comment by drchuckradio** [comment]
In Windows 10, go to Control Panel, and click the System icon.  Then click "Advanced system settings" (on the left side of the window).  This opens the System Properties window.  On the "Advanced" tab, click the button "Environment Variables."  There is a variable "Path" under your user name and System variables.  I used the variable under my user name, selected it and clicked the "Edit" button.  Add a new folder by clicking "New" and entering the path to your `svn.exe` file.  I'm using TortoiseSVN x64, so my path is `C:\Program Files\TortoiseSVN\bin`.  Once you have this path entered, the svn pacakage will find the svn executable.

**Comment by atodicebear** [comment]
That worked for me as well :)
Thx mate.
