### ISSUE TITLE
Interoperability issues with atom-tree-view-git-status

### ISSUE THREAD

**Issue by subesokun** [andischerer/atom-svn#3]
Hi, @stoneli88 created an issue on atom-tree-view-git-status (see subesokun/atom-tree-view-git-status#6) that it throws an error in case the atom-svn package was installed and trying to open a svn repository.

The root cause for this is that `repo.getWorkingDirectory()` returns `undefined` instead of the path to the project root folder. For now I've added a fix to prevent this error but I'd be great if atom-svn would return there the path of the root folder as then the svn repo status will be also shown in the tree-view.

**Comment by andischerer** [comment]
Thanks for reporting. Fixed in 0.0.7
