### ISSUE TITLE
File recognized as git instead of svn, unable to change

### ISSUE THREAD

**Issue by philip** [andischerer/atom-svn#31]
When editing a file stored in subversion, atom assumes it's a file in a git repository. For example, for a file with 12 lines atom says "master +12" instead of checking it against the subversion repository that the file is stored.

Now, I do have files with the same names in both a git repo and svn repo (don't ask, I'm stuck in the middle) so perhaps there's confusion related to this. But, they are stored in different directories locally.

Please help me debug this issue. I don't use projects, and simply go to a directory and execute `atom .` .

**Comment by 0rvar** [comment]
As an example, given this file structure:

```
rootDir/
    svnRepo/
        .svn/
        foo.txt
    gitRepo/
        .git/
        foo.txt
```

And, given that you open rootDir in atom, is svnRepo/foo.txt considered under git by atom?

**Comment by philip** [comment]
Had a fail moment, so will explain. tl;dr PEBKAC and not a bug.

This shouldn't happen but somehow did, and is unrelated to the original hypothesis. To demonstrate:
```
gitDir/
    .git
    foo.txt
rootDir/
    .git/
    A/
        B/
            svnRepo/
            .svn/
            foo.txt
```
However, rootDir/ wasn't really a git repo as I must have accidentally caused the above at some point in the recent past. Embarrassing, yes, but that's what happened. Too many windows and version control systems on the brain, perhaps.

Anyhow, git-diff understandably won the above scenario, I deleted rootDir/.git/, and all is working fine now. Thanks for this useful plugin :)
