### ISSUE TITLE
repository.getOriginURL is not a function

### ISSUE THREAD

**Issue by michael-gracy** [andischerer/atom-svn#39]
[Enter steps to reproduce below:]

Enable this package in Atom v1.30.0
Open a project that uses SVN as it's VCS
Atom Version: 1.30.0 Stable
System: MacOS 10.12.6
Thrown From: svn package, v0.0.13

### Stack Trace 
repository.getOriginURL is not a function
`TypeError: repository.getOriginURL is not a function
    at subscriptions.add.atom.project.observeRepositories (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/node_modules/metrics/lib/metrics.js:197:49)
    at Function.module.exports.Emitter.simpleDispatch (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Project.addPath (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/src/project.js:440:26)
    at Project.setPaths (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/src/project.js:358:20)
    at serviceHub.consume.provider (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/src/project.js:614:60)
    at Provider.module.exports.Provider.provide (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.activateServices (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/src/package.js:397:75)
    at Package.activateNow (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/src/package.js:233:20)
    at measure (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:875:27)
    at <anonymous>`

Commands
`                                 `

### Config
`"*":
  "activate-power-mode":
    comboMode:
      enabled: false
    particles:
      colours:
        type: "random"
      size:
        max: 2
      spawnCount:
        max: 10
      totalCount:
        max: 200
    plugins:
      playAudio: true
      screenShake: true
    screenShake:
      enabled: false
  "atom-beautify":
    bash:
      beautify_on_save: true
    executables:
      autopep8:
        path: "/usr/local/bin/autopep8"
      beautysh:
        path: "/usr/local/bin/beautysh"
    general:
      _analyticsUserId: "e12b84b1-53ec-4d4b-8a39-6651a64329c6"
    python:
      beautify_on_save: true
      default_beautifier: "pybeautifier"
  "atom-ide-ui":
    "atom-ide-console":
      consoleFontScale: 1
    "atom-ide-datatip":
      datatipDebounceDelay: 400
    "atom-ide-diagnostics-ui":
      autoVisibility: true
      showDiagnosticTraces: true
      showDirectoryColumn: true
    use: {}
  "atom-package-deps":
    ignored: []
  "autocomplete-ansible":
    pythonPaths: "/usr/local/Cellar/ansible/2.2.0.0_1/libexec/bin/python2.7"
  "autocomplete-python":
    enableTouchBar: true
    extraPaths: "C:\\Python27\\Scripts"
    pythonPaths: "C:\\Python27\\python.exe"
    useKite: false
  autosave:
    enabled: true
  "config-import-export":
    defaultPath:
      darwin: "/Users/michael.gracy/AtomBackups"
      freebsd: ""
      linux: ""
      sunos: ""
      win32: ""
  core:
    closeDeletedFileTabs: true
    customFileTypes:
      "source.ansible": [
        "yml"
      ]
    disabledPackages: [
      "language-gfm"
      "background-tips"
      "spell-check"
      "go-debug"
      "go-plus"
      "gotests"
      "ide-go"
      "language-go"
      "language-typescript"
      "linter-checkbashisms"
      "whitespace"
      "config-import-export"
      "editorconfig"
      "ide-python"
      "block-comment"
      "markdown-preview"
      "atom-ide-debugger-node"
      "atom-ide-debugger-react-native"
      "welcome"
      "go-signature-statusbar"
      "linter"
      "save-session"
      "linter-markdown"
    ]
    ignoredNames: [
      ".git"
      ".hg"
      ".svn"
      ".DS_Store"
      "._*"
      "Thumbs.db"
      "*.pyc"
      "*.pyo"
    ]
    openEmptyEditorOnStart: false
    packagesWithKeymapsDisabled: []
    projectHome: "/Users/michael.gracy/source"
    restorePreviousWindowsOnStart: "always"
    telemetryConsent: "limited"
    themes: [
      "one-dark-ui"
      "base16-tomorrow-dark-theme"
    ]
    titleBar: "custom"
    uriHandlerRegistration: "always"
  editor:
    fontSize: 15
    preferredLineLength: 120
    showIndentGuide: true
    showInvisibles: true
    softWrap: true
    tabType: "soft"
    zoomFontWhenCtrlScrolling: true
  "exception-reporting":
    userId: "012bfa7f-2aee-50f1-c72a-28283ede957e"
  "file-types":
    "":
      "*":
        yml$: "source.ansible"
      "*/group_vars/":
        "*": "source.ansible"
      "*/host_vars/":
        "*": "source.ansible"
    ".*.yml$": "source.ansible"
    ".*/group_vars/.*": "source.ansible"
    ".*/host_vars/.*": "source.ansible"
  "git-diff":
    showIconsInEditorGutter: true
  "git-plus":
    commits:
      verboseCommits: true
    experimental:
      diffBranches: true
    general:
      _analyticsUserId: "3d3d7c16-75de-4691-917d-26048044744d"
      gitPath: "/usr/local/bin/git"
      messageTimeout: 10
    remoteInteractions:
      alwaysPullFromUpstream: true
      pullBeforePush: true
  "go-config":
    gopath: "/Users/michael.gracy/source/go"
  "go-plus":
    panelDisplayMode: "closed"
  "ide-python":
    pylsPath: "/usr/local/bin/pyls"
    pylsPlugins:
      mccabe: {}
      pycodestyle:
        ignore: [
          "E121"
          "E123"
          "E126"
          "E226"
          "E24"
          "E704"
          "W503"
          "C0301"
        ]
      pydocstyle:
        enabled: true
      pyflakes:
        enabled: false
      rope_completion:
        enabled: true
  kite:
    editorMetricsEnabled: "no"
    openSidebarOnStartup: true
    showKiteTourOnStartup: false
    showKiteTourOnStatup: false
    showWelcomeNotificationOnStartup: false
    sidebarWidth: 457
  linter: {}
  "linter-ansible-linting":
    ANSIBLE0002: true
    ANSIBLE0005: true
    ANSIBLE0006: true
    ANSIBLE0010: true
    ANSIBLE0012: true
    ANSIBLE0013: true
    ansibleLintExecutablePath: "/usr/local/bin/ansible-lint"
    rulesDirDefault: true
  "linter-python":
    enableDebug: true
    executablePath: "/usr/local/bin/pylama"
    ignoreCodes: "W292,W391,C0305,W0611,D400,E501,C0301"
    lintTrigger: "File saved or modified"
    withPep257: true
    withPep8: true
    withPylint: true
  "linter-shellcheck":
    shellcheckExecutablePath: "/usr/local/bin/shellcheck"
    userParameters: "-e SC2064 -e SC2089 -e SC2086 -e SC2006 -e SC2090 -e SC2046 -e SC2140 -e SC2100 -e SC2034 -e SC2155 -e SC2045"
  "linter-ui-default":
    alwaysTakeMinimumSpace: true
    panelHeight: 128
    showProviderName: true
    showTooltip: false
    statusBarRepresents: "Current File"
    tooltipFollows: "Keyboard"
  minimap:
    absoluteMode: true
    adjustAbsoluteModeHeight: true
  "platformio-ide-terminal":
    style:
      fontSize: "12"
    toggles:
      autoClose: true
  "project-manager":
    alwaysOpenInSameWindow: true
    includeGitRepositories: true
    savePathsRelativeToHome: true
    sortBy: "title"
  "python-tools":
    pythonPath: "c:\\python27"
  "save-session":
    dataSaveFolder: "/Users/michael.gracy/.atom/packages/save-session/projects"
  script:
    cwdBehavior: "Directory of the script"
  tabs:
    enableVcsColoring: true
  "terminal-plus":
    core:
      autoRunCommand: "/usr/local/bin/bash"
      mapTerminalsTo: "Folder"
      mapTerminalsToAutoOpen: true
    style: {}
    toggles:
      autoClose: true
  "todo-show":
    findUsingRegex: "/\\b(${TODOS})[:;.,]?\\d*($|\\s.*$|[\\{\\[\\(\\#]. $)/g"
    sortAscending: false
  "tool-bar":
    iconSize: "16px"
    position: "Left"
  "tree-view":
    hideIgnoredNames: true
    hideVcsIgnoredFiles: true
    squashDirectoryNames: true
  welcome:
    showOnStartup: false
  zentabs:
    maximumOpenedTabs: 8
    neverCloseDirty: true
    neverCloseUnsaved: true
".ansible.source":
  editor:
    showIndentGuide: true
    showInvisibles: true
    softWrap: true
    softWrapAtPreferredLineLength: true
".ini.source":
  editor:
    showIndentGuide: true
    softWrap: false
    softWrapAtPreferredLineLength: true
".python.source":
  editor:
    autoIndentOnPaste: true
".shell.source":
  editor:
    softWrap: true
"linter-shellcheck":
  shellcheckExecutablePath: "/usr/local/bin/shellcheck" `

### Installed Packages
`Sublime-Style-Column-Selection@1.7.4
atom-ide-debugger-node@0.7.3
atom-ide-debugger-python@0.7.3
atom-ide-debugger-react-native@0.7.3
atom-ide-ui@0.13.0
atom-json-editor@0.4.1
atom-package-sync@0.2.6
atom-shell-commands@1.5.0
autocomplete-ansible@0.1.22
autocomplete-bash-builtins@0.3.5
autocomplete-json@5.5.2
autocomplete-python@1.10.10
busy-signal@1.4.3
comment@0.6.1
config-import-export@0.3.1
dash@1.7.1
editorconfig@2.2.2
file-icons@2.1.24
file-types@1.0.1
fold-lines@0.2.2
git-plus@8.0.2
git-time-machine@2.1.0
go-debug@1.6.2
go-plus@5.8.6
go-signature-statusbar@1.2.3
gotests@0.4.0
ide-go@0.12.3
ide-json@0.2.1
ide-python@1.0.0
intentions@1.1.5
json-colorer@1.0.0
json-generator@0.1.15
jsonlint@1.1.4
language-ansible@0.2.2
language-markdown@0.26.0
language-puppet@0.23.0
language-terraform@0.8.1
linter@2.2.0
linter-ansible-linting@1.3.3
linter-checkbashisms@0.1.5
linter-markdown@5.2.2
linter-perl@0.8.2
linter-python@3.1.2
linter-python-pep8@0.2.0
linter-shellcheck@1.5.0
linter-terraform-syntax@1.2.4
linter-ui-default@1.7.1
lipsum@0.1.0
markdown-pdf@2.2.0
markdown-preview-plus@3.5.0
markdown-scroll-sync@2.1.2
markdown-writer@2.9.0
overlay-status-icons@0.1.6
package-cop@0.2.10
platformio-ide-terminal@2.8.4
project-manager@3.3.6
python-indent@1.1.6
python-nosetests@0.2.0
python-tools@0.6.9
qolor@0.4.2
save-session
script@3.18.1
split-diff@1.5.2
ssh-config@0.14.0
svn@0.0.13
todo-show@2.3.2
tool-bar@1.1.7
tool-bar-atom@1.7.0
tool-bar-config@0.1.0
zentabs@0.8.9 

No Dev Packages`

**Comment by michael-gracy** [comment]
Happened right after the upgrade to 1.30.0 Stable.

**Comment by franmartosr** [comment]
I have the same issue after updating to 1.30.0 Stable.

**Comment by davideferre** [comment]
The same for me after updating to 1.30.0 Stable.

**Comment by reubensammut** [comment]
Had the same problem. Added the following line in lib/svn-repository.coffee and it seemed to work

`getOriginURL: (path) -> null`

under the line:

`getOriginUrl: (path) -> null`

**Comment by davideferre** [comment]
Great, this fix worked for me!

**Comment by franmartosr** [comment]
The fix worked for me as well, thanks!!!

**Comment by eescovar** [comment]
Thank you @reubensammut! Please consider creating a pull request so the author(s) can fix it as well.

**Comment by reubensammut** [comment]
@eescovar Pull request created. I was just waiting to see if it works for others

**Comment by PointedEars** [comment]
@reubensammut Your Fix WFM. But I think it is better to fix the method call than to add an additional method to cater to the wrongly spelled call. But I have not had time to look at the calling code yet.

**Comment by andischerer** [comment]
The pullrequest has been merged and a new version(0.0.14) is pushed to apm registry. Thanks to all participants to get this fix shipped. 👌

**Comment by PointedEars** [comment]
> The pullrequest has been merged and a new version(0.0.14) is pushed to apm registry. Thanks to all participants to get this fix shipped.

Thanks. It would be a good idea to find out why the method name changed, and if the old one is still necessary. AFAICS the method _call_ is not in _your_ code.

**Comment by andischerer** [comment]
> > The pullrequest has been merged and a new version(0.0.14) is pushed to apm registry. Thanks to all participants to get this fix shipped.
> 
> Thanks. It would be a good idea to find out why the method name changed, and if the old one is still necessary. AFAICS the method _call_ is not in _your_ code.

Yes your right, it would be a good idea to research why this call has changed. But i wont put any further effort in this plugin cause i've fully migrated to git and vscode. If anyone would digg a bit deeper im happy to merge the pull request.
