### ISSUE TITLE
Make treeview marking optional

### ISSUE THREAD

**Issue by redfellow** [andischerer/atom-svn#7]
Seems like this plugin chokes atom pretty badly when it's checking through the tree for changes. I have few projects where I simply have to close treeview/disable the plugin or the editor hangs up every now and then.

**Comment by redfellow** [comment]
Update: and an update seems to trigger every time I return to the editor (alt tab to browser -> back to atom). Unusable on larger repositories unless you enjoy a few seconds delay after clicking your editor multiple times per hour.

**Comment by Arcanemagus** [comment]
Fixing #20 will probably fix this as well, since fixing that requires making this package available asynchronously.

**Comment by 0rvar** [comment]
I work with a pretty large (hundreds of megs, 20k commits) svn repo daily, and the speed of this package seems good enough for me.

Have you tried with the latest version, @rnyberg ?

**Comment by 0rvar** [comment]
I'll close this, feel free to re-open if you still experience sluggishness with the tree-view
