### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by jonny981** [andischerer/atom-svn#9]
I am getting the following output when trying to install this package:

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Users\jneill1\AppData\Local\atom\app-1.1.0\resources\app\apm\bin\node.exe" "C:\Users\jneill1\AppData\Local\atom\app-1.1.0\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\jneill1\.atom\.apm\.apmrc" "--userconfig" "C:\Users\jneill1\.atom\.apmrc" "install" "C:\Users\jneill1\AppData\Local\Temp\d-115102-8252-1txtg3m\package.tgz" "--target=0.30.7" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file C:\Users\jneill1.atom.apm\es6-iterator\2.0.0\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\jneill1.atom.apm\es6-iterator\2.0.0\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by Arcanemagus** [comment]
Are you able to install any other packages? For some bizarre reason it's stripping one of the directory separators out and trying to access `C:\Users\jneill1.atom.apm\`, which doesn't exist (hence the null character).

**Comment by andischerer** [comment]
Have you tried installing the package via commandline ?

```
apm install svn
```
